FROM maven:3.8.4-openjdk-11-slim AS build
WORKDIR /
COPY src src
COPY pom.xml pom.xml
RUN mvn clean install -Dmaven.test.skip=true

FROM openjdk:11.0
LABEL "com.hsbc.ecommerceapi"="ecommerceapi-0.0.1-SNAPSHOT.jar"
LABEL version=1.0-SNAPSHOT
COPY --from=build target/ecommerceapi-0.0.1-SNAPSHOT.jar ecommerceapi-0.0.1-SNAPSHOT.jar
EXPOSE 7070
ENTRYPOINT ["java","-jar","ecommerceapi-0.0.1-SNAPSHOT.jar"]