FROM maven:3.8.4-openjdk-17 AS build
WORKDIR /
COPY src src
COPY pom.xml pom.xml
RUN mvn clean install -Dmaven.test.skip=true

FROM openjdk:17.0
LABEL "com.cts.bankingaccountapi"="bankingaccountapi"
LABEL version=1.0-SNAPSHOT
COPY --from=build target/bankingaccountapidocker-0.0.1-SNAPSHOT.jar bankingaccountapidocker-0.0.1-SNAPSHOT.jar
EXPOSE 7070
ENTRYPOINT ["java","-jar","bankingaccountapidocker-0.0.1-SNAPSHOT.jar"]